DROP TABLE IF EXISTS moyennes CASCADE;
DROP TABLE IF EXISTS evaluation CASCADE;
DROP TABLE IF EXISTS cours CASCADE;
DROP TABLE IF EXISTS salle CASCADE;
DROP TABLE IF EXISTS etudiant CASCADE;
DROP TABLE IF EXISTS intervenant CASCADE;
DROP TABLE IF EXISTS matiere CASCADE;
